### ISSUE TITLE
Schema not valid

### ISSUE THREAD

**Issue by Corfucinas** [praveenjuge/hugo-SEO-meta-tags#1]
Hi

Thanks for this repo, really good

I just came across a validation error that I haven't picked up
`<head itemscope itemtype="{{ .Site.BaseURL }}">`

On Yandex, it shows an error, seems it needs to be a valid schema as well? (https://schema.org/Article)

https://stackoverflow.com/questions/46610201/schema-org-head-html-markup-can-i-just-use-the-meta-tags

---

Can you clarify? thanks

**Comment by praveenjuge** [comment]
Hey good catch, seems like the best practices have been updated since I wrote this. The following is the correct one,

```html
 <head itemscope itemtype="https://schema.org/WebPage">
 <!-- Use the correct itemtype for your website https://schema.org/CreativeWork#subtypes -->
```

You have to use the schema identifier link there instead of the baseURL, uou can find the correct item type for your website using [this link](https://schema.org/CreativeWork#subtypes)
